{application,ex_ussd,
             [{applications,[kernel,stdlib,elixir,logger,phoenix_live_view]},
              {description,"ExUssd lets you create simple, flexible, and customizable USSD interface."},
              {modules,['Elixir.ExUssd','Elixir.ExUssd.Application',
                        'Elixir.ExUssd.Display','Elixir.ExUssd.Handler',
                        'Elixir.ExUssd.Navigation','Elixir.ExUssd.Op',
                        'Elixir.ExUssd.Ops','Elixir.ExUssd.Registry',
                        'Elixir.ExUssd.Route','Elixir.ExUssd.Utils',
                        'Elixir.Inspect.ExUssd',
                        'Elixir.Phoenix.ExUssd.ErrorView',
                        'Elixir.Phoenix.ExUssd.LayoutView',
                        'Elixir.Phoenix.ExUssd.PageLive',
                        'Elixir.Phoenix.ExUssd.PageView',
                        'Elixir.Phoenix.ExUssd.Web']},
              {registered,[]},
              {vsn,"0.1.3"},
              {mod,{'Elixir.ExUssd.Application',[]}}]}.
