name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you @${{ github.actor }} for your issue! We are glad you contributed!"
        pr-message: "Thank you @${{ github.actor }} for your first pull Request!"